baseURL = "https://shoogle.us/district-of-columbia"
languageCode = "en-US"
title = "District of Columbia"
theme = "ln-base-en"

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML", "JSON"]

[params]
  site = "Shoogle"
  org = "lokal-ninja"
  repo = "district-of-columbia"
